package no.nav.bidrag.domene.enums

enum class Avvikstype {
    PERIODER_OVERLAPPER,
    PERIODER_HAR_OPPHOLD,
    NULL_VERDI_I_DATO,
    DATO_FOM_ETTER_DATO_TIL,
    PERIODE_MANGLER_DATA,
    UGYLDIG_INNTEKT_TYPE,
    UGYLDIG_INNTEKT_PERIODE,
    OVERLAPPENDE_INNTEKT,
}
